
server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: menu_manager-service
          uri: http://localhost:8000/
          predicates:
            - Path=/menu/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://localhost:8001/
          predicates:
            - Path=/user/**
#          filters:
#            - AuthenticationFilter

        - id: restaurant-service
          uri: http://localhost:8002/
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: sales-service
          uri: http://localhost:8003/
          predicates:
            - Path=/sales/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: http://localhost:8004/
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter